apiVersion: apps/v1
kind: Deployment
metadata:
  name: appName
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appName
  template:
    metadata:
      labels:
        app: appName
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: appName
        image: sociallmek8sacr.azurecr.io/identityservice:${{ github.sha }}
        # Removed envs
        envFrom:
        - secretRef:
            name: env-secrets
        imagePullPolicy: Always
        # command: ["/bin/sh"]
        # args: ["-c", "while true; do echo Container Running; sleep 3;done"]
        resources:
          requests:
            cpu: 50m
            memory: 512Mi
          limits:
            cpu: 250m
            memory: 1024Mi
        ports:
        - containerPort: 8080
        # env:
        #   - name: LOAD_BALANCER_IP
        #     value: 20.71.3.246
---
apiVersion: v1
kind: Service
metadata:
  name: appName
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: appName
