# Generated by Django 3.1 on 2021-01-21 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20210120_0810"),
    ]

    operations = [
        migrations.CreateModel(
            name="MuteAndBlockedProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blocked", models.BooleanField(default=False)),
                ("muted", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "unwanted_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unwanted_uesr",
                        to="core.profile",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to="core.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.AddConstraint(
            model_name="muteandblockedprofile",
            constraint=models.UniqueConstraint(
                fields=("user_id", "unwanted_user"), name="unique_unwanted"
            ),
        ),
    ]
