# Generated by Django 3.1 on 2021-01-29 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210121_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserUnFollowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('un_followed_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='un_followed', to='core.profile')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='un_following', to='core.profile')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddConstraint(
            model_name='userunfollowing',
            constraint=models.UniqueConstraint(fields=('user_id', 'un_followed_user_id'), name='unique_un_followed'),
        ),
    ]
