# Generated by Django 3.1 on 2021-01-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210129_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='sociallist',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
