# Generated by Django 3.1 on 2021-02-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210129_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfollowing',
            name='following_user_id',
        ),
        migrations.RemoveField(
            model_name='userfollowing',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='userunfollowing',
            name='un_followed_user_id',
        ),
        migrations.RemoveField(
            model_name='userunfollowing',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='sociallist',
            name='created_by',
        ),
        migrations.AddField(
            model_name='sociallist',
            name='created_by_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sociallist',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='listfollower',
            name='list_following_user',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='MuteAndBlockedProfile',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='UserFollowing',
        ),
        migrations.DeleteModel(
            name='UserUnFollowing',
        ),
    ]
